version: '3'

services:
  mysql:
    image: mysql:8.4.3
    environment:
      MYSQL_DATABASE: 'yeahpeu'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '23214:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'

volumes:
    mysqldata:
