version: '3.8'

services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql-container-yeahpeu
    volumes:
      - /home/ubuntu/mysql-data-test:/var/lib/mysql
    restart: always
    env_file:
      - .env_mysql
    ports:
      - "3306:3306"
    networks:
      - backend_network

  app:
    image: ujw4179/yeahpeu_backend:lts
    container_name: yeahpeu-backend-test
    volumes:
      - /home/ubuntu/yeahpeu-backend-app-test:/app/data
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - backend_network
    ports:
      - "8080:8080"

networks:
  backend_network:
    driver: bridge
